### PR TITLE
fixed #25, replaced sample action index

### LINKED ISSUE #25: Sample Action Available also when the agent is not on rocks
When the agent is not on a rock, it can sample, but it shouldn't be allowed.
A wrong action index causes that in actions.jl at line 2.
```
const BASIC_ACTIONS_DICT = Dict(
                                :north => 1, 
                                :east => 2,
                                :south => 3,
                                :west => 4,
                                :sample => 5)

function POMDPs.actions(pomdp::RockSamplePOMDP{K}, s::RSState) where K
    if in(s.pos, pomdp.rocks_positions) # slow? pomdp.rock_pos is a vec 
        return actions(pomdp)
    else
        # sample not available
        return 2:N_BASIC_ACTIONS+K
    end
end
```
as you can see if the agent is on a rock the function returns all the actions except the north action but the comment says it should return all actions except the sample one.

### PR DESCRIPTION
**Pull request by LorenzoBonanni**

### CODE REVIEW

**Comment by zsunberg** [comment]
Hmm... it does seem like we need to fix #25, but currently the tests are failing for some reason.

**Comment by LorenzoBonanni** [comment]
I forgot to update the tests according to the new action indexes. I'll fix it in a couple of minutes.

**Comment by LorenzoBonanni** [comment]
@zsunberg now the tests pass

**Comment by zsunberg** [comment]
Great Thank you @LorenzoBonanni ! Do you think it is a good idea to tag a new version in the registry after this fix?

**Comment by zsunberg** [comment]
Since the actions could be considered part of the "public interface", and we changed that, I think we should tag version 0.2.0.

**Comment by LorenzoBonanni** [comment]
Yeah, that's fine the pull requests didn't add anything ground breaking adding 0.2.0 makes sense

**Pull request merged**
